### PR TITLE
Equality not assignment

### PR DESCRIPTION
**Pull request by gdiggs**

### CODE REVIEW

**Comment by pbrisbin** [comment]
If only there were tools to catch this...

**Comment by wfleming** [comment]
The classic error, only slightly less well known than "never get involved in a land war in Asia".

**Comment by wfleming** [comment]
This LGTM. I'm horrified neither PHP Code Sniffer nor PHPMD caught it. Is there another rule set that would have?

**Comment by gdiggs** [comment]
Closing this in favor of something like https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/40

**Pull request closed without merging**
